// Diễn giải từ giáo trình đã cung cấp. Trang tham chiếu là số in trên trang.
export const chapters=[
{id:4,title:'Quyền lực để phụng sự',short:'Đảng & Nhà nước',image:'assets/assembly-1946.jpg',intro:'Lãnh đạo, quyền làm chủ, pháp quyền và trách nhiệm trước nhân dân.',items:[
['Đảng lãnh đạo, Đảng phụng sự','4.1','72–80','Sự ra đời của Đảng kết hợp chủ nghĩa Mác–Lênin, phong trào công nhân và phong trào yêu nước Việt Nam.','Đảng phải có đạo đức, văn minh, đặt lợi ích dân tộc và nhân dân lên trên lợi ích riêng. Tập trung dân chủ, tự phê bình và phê bình, kỷ luật tự giác, đoàn kết và liên hệ với nhân dân là những nguyên tắc tổ chức.','Một tổ chức làm gì để lời nói đi cùng việc làm?'],
['Trách nhiệm người cán bộ','4.1','79–82','Phẩm chất và năng lực thể hiện trong công việc, trách nhiệm và quan hệ với nhân dân.','Cán bộ cần học hỏi, chủ động, gần dân; chống tham ô, lãng phí, quan liêu. Đánh giá, đào tạo và sử dụng cán bộ phải công tâm; kiểm tra đi cùng giúp đỡ và sửa chữa khuyết điểm.','Bạn sẽ công khai trách nhiệm của mình khi được giao việc chung thế nào?'],
['Của dân · Do dân · Vì dân','4.2.1','83–87','Nhân dân là chủ thể quyền lực; Nhà nước do nhân dân xây dựng, phục vụ lợi ích và nguyện vọng chính đáng của nhân dân.','Dân là chủ nói đến vị thế; dân làm chủ nhấn mạnh thực hiện quyền, nghĩa vụ và tham gia quản lý. Cán bộ phải có cả phẩm chất và năng lực, không đặc quyền, đặc lợi.','Người dân có thể tham gia và giám sát công việc chung bằng cách nào?'],
['Pháp quyền và nhân nghĩa','4.2.2','88–90','Quản lý bằng Hiến pháp và pháp luật gắn với tôn trọng, bảo vệ quyền con người.','Lập pháp, thi hành, giáo dục pháp luật và giám sát của nhân dân đều quan trọng. Cán bộ cần gương mẫu; thực thi công bằng, không tùy tiện. Pháp luật còn có tính nhân văn, giáo dục và bảo vệ người yếu thế.','Vì sao công bằng cần đi cùng tôn trọng con người?'],
['Kiểm soát quyền lực','4.2.3','91, 94','Quyền lực được nhân dân giao cần được kiểm soát để ngăn lạm quyền và bảo vệ niềm tin.','Phát huy dân chủ, sự tham gia của nhân dân, kiểm tra và kỷ luật. Kết hợp giáo dục đạo đức, nêu gương với pháp luật nghiêm minh để phòng chống tham ô, lãng phí, quan liêu.','Một quyết định ảnh hưởng tập thể nên được kiểm tra ra sao?'],
['Xây dựng và tự chỉnh đốn','4.3','95–97','Xây dựng Đảng trong sạch, vững mạnh và Nhà nước phục vụ nhân dân là công việc thường xuyên.','Đường lối cần phù hợp thực tiễn; tổ chức thực hiện, kiểm tra và tự sửa chữa phải đi cùng nhau. Hoàn thiện pháp luật gắn với thi hành hiệu quả; đội ngũ cần năng lực, đạo đức và trách nhiệm rõ ràng.','Nhóm của bạn có cơ chế nhận lỗi và sửa lỗi không?']]},
{id:5,title:'Khác biệt cùng một hướng',short:'Đại đoàn kết',image:'assets/telegram-1946.jpg',intro:'Tìm lợi ích chung, xây dựng niềm tin và tổ chức sức mạnh của nhân dân.',items:[
['Đoàn kết là chiến lược','5.1.1','99–100','Đại đoàn kết toàn dân tộc có ý nghĩa chiến lược, lâu dài và quyết định thành công của cách mạng.','Đoàn kết là mục tiêu, nhiệm vụ hàng đầu, không chỉ là biện pháp nhất thời. Nhu cầu quần chúng cần chuyển thành hành động tự giác, có tổ chức.','Mục tiêu chung có đủ tạo đoàn kết bền vững không?'],
['Ai thuộc khối đoàn kết?','5.1.2','101–102','Chủ thể là toàn thể nhân dân và những người Việt Nam yêu nước ở trong, ngoài nước.','Không phân biệt dân tộc, tôn giáo, nghề nghiệp, giới tính, tuổi tác, thành phần xã hội khi cùng hướng đến lợi ích chung. Nền tảng là liên minh công nhân–nông dân–trí thức; đoàn kết trong Đảng có vai trò hạt nhân.','Ai thường bị bỏ quên khi chúng ta lập một nhóm?'],
['Ba điều kiện tạo niềm tin','5.1.3','102–103','Kế thừa truyền thống yêu nước, nhân nghĩa, đoàn kết; có lòng khoan dung và niềm tin vào nhân dân.','Khoan dung giúp phát huy điều tốt ở mỗi người, không đồng nghĩa bỏ qua nguyên tắc. Tin dân đi cùng yêu dân, dựa vào dân và phát huy khả năng của nhân dân.','Bạn có thể lắng nghe người khác ý kiến mà vẫn giữ nguyên tắc không?'],
['Từ tập hợp đến tổ chức','5.1.4','103–105','Mặt trận dân tộc thống nhất tập hợp rộng rãi các tổ chức và cá nhân yêu nước.','Nền tảng liên minh công nhân–nông dân–trí thức dưới sự lãnh đạo của Đảng; lấy lợi ích nước và dân làm mục tiêu. Hiệp thương dân chủ; đoàn kết lâu dài, chân thành, chặt chẽ, giúp nhau tiến bộ; tìm điểm chung, tôn trọng khác biệt chính đáng.','Thảo luận dân chủ khác đồng ý cho xong ở đâu?'],
['Dân vận và sức mạnh chung','5.1.5','105–106','Xây dựng đoàn kết qua dân vận, các đoàn thể phù hợp và tập hợp các đoàn thể trong Mặt trận.','Giải thích, vận động cần phù hợp hoàn cảnh, nguyện vọng và lợi ích từng đối tượng. Tổ chức còn bảo vệ quyền lợi, kết nối nhân dân với Đảng và tạo điều kiện hành động.','Hoạt động cộng đồng nên bắt đầu từ nhu cầu nào?'],
['Tự chủ và kết nối quốc tế','5.2–5.3','107–117','Đoàn kết quốc tế kết hợp sức mạnh dân tộc với sức mạnh thời đại, trên nền tảng độc lập, tự chủ.','Hợp tác vì hòa bình, độc lập dân tộc, dân chủ và tiến bộ xã hội; tôn trọng bình đẳng, quyền tự quyết. Nội lực có vai trò quyết định, hỗ trợ bên ngoài phát huy qua nội lực. Vận dụng cần hài hòa lợi ích và tôn trọng khác biệt chính đáng.','Hợp tác thế nào để hỗ trợ nhau và giữ tự chủ?']]},
{id:6,title:'Giá trị trở thành đời sống',short:'Văn hóa & con người',image:'assets/stilt-house.jpg',intro:'Văn hóa định hướng, đạo đức làm gốc, con người vừa là mục tiêu vừa là động lực.',items:[
['Văn hóa: mục tiêu và động lực','6.1','120–125','Văn hóa gắn với toàn bộ đời sống, có quan hệ qua lại với kinh tế, chính trị và xã hội.','Giữ bản sắc dân tộc, tiếp thu có chọn lọc tinh hoa nhân loại. Văn hóa là một mặt trận, phục vụ nhân dân; nhân dân vừa sáng tạo, đánh giá, vừa hưởng thụ văn hóa.','Sản phẩm văn hóa của nhóm phục vụ ai, mang giá trị gì?'],
['Đức và tài cùng phát triển','6.2.1','126–130','Đạo đức là nền tảng; tài năng giúp thực hiện công việc. Phẩm chất cần được chứng minh bằng hành động.','Trung với nước, hiếu với dân thể hiện trong trách nhiệm với đất nước, phục vụ, tin và học hỏi nhân dân. Không tách năng lực chuyên môn khỏi trách nhiệm và nhân cách.','Giỏi một việc nhưng thiếu trách nhiệm sẽ ảnh hưởng người khác ra sao?'],
['Cần · Kiệm · Liêm · Chính','6.2.2','130–134','Cần: lao động có kế hoạch, sáng tạo. Kiệm: tiết kiệm thời gian, sức lực, của cải. Liêm: trong sạch. Chính: ngay thẳng.','Chí công vô tư là công tâm, đặt lợi ích chung lên trên, không thiên vị vì lợi ích riêng; không phủ nhận nhu cầu cá nhân chính đáng. Yêu thương con người và tinh thần quốc tế trong sáng thể hiện bằng hành động, tôn trọng, giúp đỡ và đoàn kết.','Bạn thực hành tiết kiệm và công tâm trong dự án bằng việc gì?'],
['Đạo đức: việc làm mỗi ngày','6.2.3','134–138','Nói đi đôi với làm, nêu gương; xây đi đôi với chống; tu dưỡng đạo đức suốt đời.','Xây dựng điều tốt gắn chống điều xấu, lấy xây dựng làm chính; giáo dục và tự giáo dục cùng quan trọng. Tu dưỡng diễn ra trong việc cụ thể hằng ngày, không phải danh hiệu đạt rồi giữ mãi.','Lời hứa nhỏ nào bạn có thể thực hiện hôm nay?'],
['Con người: mục tiêu và động lực','6.3','139–142','Con người có trí lực, tâm lực, thể lực và sống trong những quan hệ xã hội cụ thể.','Nâng cao đời sống vật chất, tinh thần của con người là mục tiêu; nhân dân là chủ thể sáng tạo lịch sử. Trồng người là chiến lược lâu dài: giáo dục, tổ chức, nêu gương, tự rèn luyện phát triển phẩm chất và năng lực.','Phát triển bản thân đóng góp gì cho cộng đồng?'],
['Từ kiến thức đến việc làm','6.4','143–150','Xây dựng môi trường văn hóa lành mạnh, phát triển con người toàn diện, rèn đạo đức trong học tập và đời sống.','Kết hợp bản sắc dân tộc với tính nhân văn, dân chủ, khoa học; phát huy sáng tạo và học tập suốt đời. Sinh viên bắt đầu từ trung thực, trách nhiệm, khiêm tốn, đồng cảm và mục đích học tập gắn đóng góp xã hội.','Chọn một việc nhỏ, một thời hạn và một người cùng thực hiện.']]}
];
const chapterImages=[
 ['portrait-1946','stilt-room','assembly-1946','national-assembly','museum-hanoi','museum-interior'],
 ['expats-1946','assembly-1946','museum-hanoi','national-assembly','portrait-1946','telegram-1946'],
 ['van-mieu','portrait-1946','stilt-room','museum-interior','stilt-house','museum-hanoi']
];
export const exhibits=chapters.flatMap((c,z)=>c.items.map((a,i)=>({id:`${c.id}-${i}`,title:a[0],section:a[1],pages:a[2],lead:a[3],body:a[4],question:a[5],chapter:c.id,zone:z,index:i,image:`assets/${chapterImages[z][i]}.jpg`})));
export const media={
'assets/assembly-1946.jpg':{caption:'Hồ Chí Minh sau giờ họp Quốc hội tại Nhà hát Lớn, Hà Nội, 1946.',credit:'Trung tâm Lưu trữ quốc gia III · ảnh A36',license:'Phạm vi công cộng theo Wikimedia Commons',url:'https://commons.wikimedia.org/wiki/File:Chủ_tịch_Hồ_Chí_Minh_tan_giờ_họp_Quốc_hội_tại_Nhà_Hát_Lớn_-_Hà_Nội,_năm_1946_(Trung_tâm_Lưu_trữ_quốc_gia_III,_Mục_lục_Tài_liệu_ảnh_A36).jpg'},
'assets/telegram-1946.jpg':{caption:'Điện tín Hồ Chí Minh gửi Harry S. Truman, 28/02/1946. Minh họa hoạt động đối ngoại, không chứng minh kết quả hợp tác.',credit:'NARA · hồ sơ 305263',license:'Phạm vi công cộng · tài liệu lưu trữ Hoa Kỳ',url:'https://commons.wikimedia.org/wiki/File:Telegram_Hochiminh.jpg'},
'assets/stilt-house.jpg':{caption:'Nhà sàn tại Hà Nội, ảnh chụp năm 2017. Ảnh di sản minh họa, không phải ảnh sự kiện của từng bài.',credit:'Richard Mortel',license:'CC BY 2.0',licenseUrl:'https://creativecommons.org/licenses/by/2.0/',url:"https://commons.wikimedia.org/wiki/File:Ho_Chi_Minh's_Stilt_House,_Hanoi_(2)_(24622695398).jpg"},
'assets/portrait-1946.jpg':{caption:'Chân dung Hồ Chí Minh, khoảng năm 1946. Ảnh minh họa nhân vật, không minh họa trực tiếp từng luận điểm.',credit:'Tác giả chưa xác định · Wikimedia Commons',license:'Phạm vi công cộng theo hồ sơ Commons',url:'https://commons.wikimedia.org/wiki/File:Ho_Chi_Minh_-_1946_Portrait.jpg'},
'assets/expats-1946.jpg':{caption:'Hồ Chí Minh trò chuyện với kiều bào tại Pháp, 1946. Tư liệu minh họa kết nối người Việt ở nước ngoài.',credit:'Tác giả chưa xác định · Wikimedia Commons',license:'Phạm vi công cộng theo hồ sơ Commons',url:'https://commons.wikimedia.org/wiki/File:Ho_Chi_Minh_with_Vietnamese_expats_in_France,_1946.jpg'},
'assets/stilt-room.jpg':{caption:'Phòng tại nhà sàn Hồ Chí Minh, ảnh chụp năm 2009. Minh họa không gian di sản, không phải chứng cứ cho phẩm chất đạo đức.',credit:'Dennis G. Jarvis',license:'CC BY-SA 2.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/2.0/',url:'https://commons.wikimedia.org/wiki/File:Room_at_Stilt_House.jpg'},
'assets/museum-interior.jpg':{caption:'Không gian Bảo tàng Hồ Chí Minh, ảnh của Syced. Minh họa hoạt động gìn giữ ký ức và di sản.',credit:'Syced',license:'CC0',licenseUrl:'https://creativecommons.org/publicdomain/zero/1.0/',url:'https://commons.wikimedia.org/wiki/File:Ho_Chi_Minh_museum.jpg'},
'assets/museum-hanoi.jpg':{caption:'Bảo tàng Hồ Chí Minh tại Hà Nội, năm 2018. Ảnh công trình di sản minh họa, không phải hiện vật số hóa của triển lãm này.',credit:'Jp16103',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',url:'https://commons.wikimedia.org/wiki/File:Ho_Chi_Minh_Museum.jpg'},
'assets/national-assembly.jpg':{caption:'Tòa nhà Quốc hội Việt Nam tại Hà Nội. Ảnh công trình đương đại minh họa chủ đề Nhà nước, không phải ảnh Quốc hội năm 1946.',credit:'David Stanley',license:'CC BY 2.0',licenseUrl:'https://creativecommons.org/licenses/by/2.0/',url:'https://commons.wikimedia.org/wiki/File:Vietnam_National_Assembly_Building.jpg'},
'assets/van-mieu.jpg':{caption:'Văn Miếu Trấn Biên, Đồng Nai, tháng 9/2019. Ảnh di sản minh họa văn hóa và truyền thống học tập, không phải hiện vật của Hồ Chí Minh.',credit:'Phương Huy',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',url:'https://commons.wikimedia.org/wiki/File:Văn_Miếu_Trấn_Biên_Đồng_Nai,_ngày_27_tháng_9_năm_2019_(5).jpg'}};
export const flow=['Nhân dân','Tìm điểm chung','Tập hợp','Tổ chức','Đại đoàn kết','Sức mạnh chung'];
export const flowNotes=['Mọi người Việt Nam yêu nước; không chỉ một nhóm giống nhau.','Lợi ích nước và dân là điểm quy tụ; tôn trọng khác biệt chính đáng.','Vận động, kết nối cá nhân và đoàn thể phù hợp.','Mặt trận và hiệp thương dân chủ phối hợp hành động.','Niềm tin, chân thành và hỗ trợ nhau tiến bộ lâu dài.','Hành động vì mục tiêu chung phát huy sức mạnh tập thể.'];
