import * as THREE from 'three';
const $=id=>document.getElementById(id),photo='https://ichef.bbci.co.uk/ace/ws/640/cpsprodpb/5EF2/production/_107660342_gettyimages-541072067.jpg.webp';
const zones=[{title:'Sức mạnh đại đoàn kết',description:'Kết nối mọi lực lượng vì một mục tiêu chung. Chương 5, các mục 5.1.1–5.1.5.',pos:[-4.5,2.3,1.5],look:[-5.9,2.2,-3],items:[['Vai trò & lực lượng','Đại đoàn kết có ý nghĩa chiến lược, quyết định thành công của cách mạng. Chủ thể là toàn thể nhân dân và những người Việt Nam yêu nước. Nền tảng là công nhân, nông dân và trí thức.','Giáo trình tr. 99–101'],['Điều kiện đoàn kết','Kế thừa truyền thống yêu nước, nhân nghĩa, đoàn kết; có lòng khoan dung, độ lượng và niềm tin vào nhân dân.','Giáo trình tr. 102–103'],['Mặt trận & dân vận','Mặt trận dân tộc thống nhất là hình thức tổ chức. Các nguyên tắc gồm nền tảng liên minh công nhân–nông dân–trí thức dưới sự lãnh đạo của Đảng, mục tiêu vì nước vì dân, hiệp thương dân chủ và đoàn kết lâu dài, chân thành. Phương thức: dân vận, xây dựng đoàn thể phù hợp và tập hợp trong Mặt trận.','Giáo trình tr. 103–106']]},{title:'Nhà nước vì nhân dân',description:'Pháp quyền, trong sạch và trách nhiệm phụng sự. Chương 4, mục 4.2.2–4.3.',pos:[0,2.2,1],look:[0,2.4,-5.8],items:[['Nhà nước pháp quyền','Giới thiệu vai trò của Hiến pháp và pháp luật trong tổ chức và hoạt động của Nhà nước.','Mục 4.2.2 · Giới thiệu phạm vi demo'],['Trong sạch, vững mạnh','Giới thiệu trách nhiệm cán bộ và việc phòng, chống những biểu hiện làm suy giảm niềm tin của nhân dân.','Mục 4.2.3 · Nội dung chi tiết cần đối chiếu giáo trình'],['Xây dựng & chỉnh đốn','Giới thiệu việc vận dụng vào xây dựng Đảng trong sạch, vững mạnh và xây dựng Nhà nước phục vụ nhân dân.','Mục 4.3 · Giới thiệu phạm vi demo']]},{title:'Văn hóa & con người',description:'Những giá trị tiếp nối trong đời sống. Chương 6, các mục nhóm lựa chọn.',pos:[4.5,2.3,1.5],look:[5.9,2.2,-3],items:[['Văn hóa','Khám phá tư tưởng về văn hóa và việc xây dựng, phát triển văn hóa hiện nay.','Mục 6.1, 6.4 · Giới thiệu phạm vi demo'],['Đạo đức','Khám phá tư tưởng về đạo đức và việc tu dưỡng, xây dựng đạo đức cách mạng.','Mục 6.2, 6.4 · Giới thiệu phạm vi demo'],['Con người','Khám phá quan điểm về con người và sự quan tâm, bồi dưỡng, phát triển con người.','Mục 6.3–6.4 · Giới thiệu phạm vi demo']]}];
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('status').innerHTML='Trình duyệt chưa mở được WebGL. <a href="exhibition.html">Xem bản triển lãm ảnh ↗</a>';throw e}renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;$('scene').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#172019');scene.fog=new THREE.Fog('#172019',20,40);const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,60);camera.position.set(8,6.5,13);const look=new THREE.Vector3(0,1.4,-2),targetPos=new THREE.Vector3(7,5.5,10),targetLook=look.clone();scene.add(new THREE.HemisphereLight('#fff3d9','#49463a',2));
const mat=(color,roughness=.7,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});const stone=mat('#ddd4be'),green=mat('#33483b'),gold=mat('#b18d4f',.3,.65),wood=mat('#755335');
function box(w,h,d,x,y,z,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
box(14,.2,17,0,-.1,0,mat('#b2a68b',.35));box(14,5.6,.3,0,2.8,-6,stone);box(.3,5.6,13,-7,2.8,-.5,stone);box(.3,5.6,13,7,2.8,-.5,stone);box(14,.14,13,0,5.6,-.5,mat('#8c897b'));for(let x=-7;x<=7;x+=2)box(.012,.007,16,x,.012,0,mat('#827b68'));for(let z=-7;z<=8;z+=2)box(14,.007,.012,0,.013,z,mat('#827b68'));for(let x of [-6.7,6.7]){for(let z of [-5,0,5])box(.35,5.4,.35,x,2.7,z,green)}
for(let x of [-4,0,4]){box(.08,.08,10,x,5.35,-.5,mat('#282f27'));const light=new THREE.SpotLight('#ffe5b8',70,20,.65,.65,1.6);light.position.set(x,5.1,0);light.target.position.set(x,2,-5.5);light.castShadow=true;light.shadow.mapSize.set(1024,1024);scene.add(light,light.target);box(.18,.12,.3,x,5.15,-1,gold)}const sun=new THREE.DirectionalLight('#fff1d1',2);sun.position.set(3,7,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-10;sun.shadow.camera.right=10;sun.shadow.camera.top=10;sun.shadow.camera.bottom=-10;scene.add(sun);
function textTexture(text,sub,bg='#e9dfc8',fg='#273c31'){const c=document.createElement('canvas');c.width=1024;c.height=512;let g=c.getContext('2d');g.fillStyle=bg;g.fillRect(0,0,c.width,c.height);g.fillStyle=fg;g.textAlign='center';g.font='48px Georgia';g.fillText(text,512,245);g.font='18px sans-serif';g.fillText(sub,512,305);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function planeTexture(t,w,h,x,y,z,rot=0){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:t}));mesh.position.set(x,y,z);mesh.rotation.y=rot;scene.add(mesh);return mesh}
planeTexture(textTexture('DẤU ẤN','TƯ TƯỞNG VÀ ĐỜI SỐNG','#33483b','#e8d9b8'),4.8,1.6,0,4.1,-5.81);
const objects=[],hotspots=[];let zone=-1;const loader=new THREE.TextureLoader();let loaded=0;
for(let zi=0;zi<3;zi++){for(let i=0;i<3;i++){let group=new THREE.Group();let x=zi===1?(i-1)*3.3:zi===0?-6.79:6.79;let z=zi===1?-5.78:-4.5+i*3;let rot=zi===1?0:zi===0?Math.PI/2:-Math.PI/2;group.position.set(x,2.5,z);group.rotation.y=rot;scene.add(group);const frame=new THREE.Mesh(new THREE.BoxGeometry(2.35,1.72,.12),gold);frame.castShadow=true;group.add(frame);const mount=new THREE.Mesh(new THREE.PlaneGeometry(2.16,1.53),new THREE.MeshBasicMaterial({color:'#e9dfc8'}));mount.position.z=.065;group.add(mount);const pic=new THREE.Mesh(new THREE.PlaneGeometry(1.98,1.32),new THREE.MeshBasicMaterial({map:textTexture(zones[zi].items[i][0],'TƯ LIỆU / HCM202')}));pic.position.z=.08;group.add(pic);loader.load(photo,t=>{t.colorSpace=THREE.SRGBColorSpace;pic.material.map=t;pic.material.needsUpdate=true;loaded++;},undefined,()=>{});const plaque=new THREE.Mesh(new THREE.PlaneGeometry(2.15,.45),new THREE.MeshBasicMaterial({map:textTexture(zones[zi].items[i][0],'0'+(i+1))}));plaque.position.set(0,-1.17,.07);group.add(plaque);pic.userData={zi,i};objects.push(pic);const b=document.createElement('button');b.className='hotspot';b.textContent='+';b.setAttribute('aria-label','Xem '+zones[zi].items[i][0]);b.onclick=()=>open(zi,i);$('labels').append(b);hotspots.push({b,group,zi});}}
// Central display: a sculptural open book and brass rings.
box(1.8,1.1,1.3,0,.55,-.5,stone);box(1.9,.08,1.4,0,1.15,-.5,gold);const book=new THREE.Group();book.position.set(0,1.5,-.5);book.rotation.x=-.35;for(let side of [-1,1]){const page=new THREE.Mesh(new THREE.BoxGeometry(.8,.07,1.05),mat('#f4e6cb'));page.position.x=side*.39;page.rotation.z=side*.2;book.add(page)}scene.add(book);for(let i=0;i<2;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.65+i*.12,.025,12,64),gold);ring.position.set(0,2.7,-.5);ring.rotation.y=i*Math.PI/2;scene.add(ring)}for(let x of [-3,3]){box(2.1,.16,.65,x,.65,3,wood);for(let dx of [-.8,.8])box(.1,.65,.5,x+dx,.32,3,green)}
function open(zi,i){const item=zones[zi].items[i];$('detail').replaceChildren();let h=document.createElement('h2');h.textContent=item[0];let p=document.createElement('p');p.textContent=item[1];let small=document.createElement('small');small.textContent=item[2];let image=document.createElement('img');image.src=photo;image.alt='Ảnh tư liệu minh họa, BBC / Getty';let source=document.createElement('p');source.innerHTML='<a href="https://www.bbc.com/vietnamese/vietnam-48829610" target="_blank" rel="noopener">Nguồn ảnh BBC / Getty ↗</a> · Ảnh minh họa dùng chung trong demo.';$('detail').append(h,image,p,small,source);$('modal').showModal()}
function select(zi){zone=zi;const r=zones[zi];targetPos.set(...r.pos);targetLook.set(...r.look);$('title').textContent=r.title;$('description').textContent=r.description;$('art-list').replaceChildren();r.items.forEach((it,i)=>{const b=document.createElement('button');b.textContent='0'+(i+1)+' / '+it[0];b.onclick=()=>open(zi,i);$('art-list').append(b)});document.querySelectorAll('[data-zone]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.zone)===zi));$('status').textContent='Kéo nhẹ để nhìn quanh · Chạm dấu + để xem tư liệu.'}
document.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>select(Number(b.dataset.zone)));$('overview').onclick=()=>{zone=-1;targetPos.set(7,5.5,10);targetLook.set(0,1.4,-2);$('title').textContent='Sảnh Dấu Ấn';$('description').textContent='Chọn một khu trưng bày để tiến đến gần.';$('art-list').replaceChildren();document.querySelectorAll('[data-zone]').forEach(b=>b.setAttribute('aria-pressed','false'))};$('close').onclick=()=>$('modal').close();$('modal').addEventListener('close',()=>$('detail').replaceChildren());$('film').onclick=()=>{$('detail').innerHTML='<h2>Thước phim tư liệu</h2><iframe title="Tư tưởng đại đoàn kết" src="https://www.youtube-nocookie.com/embed/_W_eKdsBQd0" allow="encrypted-media; picture-in-picture" allowfullscreen></iframe><p><a href="https://www.youtube.com/watch?v=_W_eKdsBQd0" target="_blank" rel="noopener">Xem trên YouTube ↗</a></p>';$('modal').showModal()};
let down=null,moved=false;const ray=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};moved=false;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!down)return;let dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.abs(dx)+Math.abs(dy)>3)moved=true;targetLook.x-=dx*.007;targetLook.y=THREE.MathUtils.clamp(targetLook.y+dy*.005,.8,4);down={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',e=>{if(!moved){ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=ray.intersectObjects(objects)[0];if(hit)open(hit.object.userData.zi,hit.object.userData.i)}down=null});renderer.domElement.addEventListener('pointercancel',()=>down=null);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});const v=new THREE.Vector3();let last=performance.now();function animate(now){const dt=Math.min((now-last)/1000,.1);last=now;const a=1-Math.exp(-dt*4);camera.position.lerp(targetPos,a);look.lerp(targetLook,a);camera.lookAt(look);renderer.render(scene,camera);for(const h of hotspots){h.group.getWorldPosition(v);v.project(camera);h.b.hidden=(zone!==h.zi)||v.z>1||Math.abs(v.x)>1||Math.abs(v.y)>1;h.b.style.left=(v.x*.5+.5)*innerWidth+'px';h.b.style.top=(-v.y*.5+.5)*innerHeight+'px'}requestAnimationFrame(animate)}requestAnimationFrame(animate);$('status').textContent='Không gian đã sẵn sàng. Chọn một khu để bắt đầu.';
